sudo: false

language: node_js
node_js:
  - node
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules

script:
  - npm run test:coveralls
after_success:
  - npm run coverage