const users = [
  {
    id: 1,
    firstName: 'dsfgsdf',
    lastName: 'Maina',
    email: 'karis@gmail.com',
    address: 'sdkjhk',
    password: '$2b$10$.DgqXG93qUTq8a0ha88SBew2bZBzTK9Ymi6qeX49YWLffFRNkLSaK',
    bio: 'animal lover',
    occupation: 'teacher',
    expertise: 'dfgsdfhdfg',
    isMentor: true,
    admin: false,
  },
  {
    id: 2,
    firstName: 'Boniface',
    lastName: 'Maina',
    email: 'karisbm@gmail.com',
    address: 'sdkjhk',
    password: '$2b$10$267Xvq6TUQl6dq0xnAbiCuKhqfBOwCzeJ7Y4wH5ZlGl/g7SLcO6mO',
    bio: 'kayaking instructor',
    occupation: 'teacher',
    expertise: 'swimming',
    isMentor: false,
    admin: true,
  },
  {
    id: 3,
    firstName: 'Sam',
    lastName: 'Kimundu',
    email: 'sam@gmail.com',
    address: 'sdkjhk',
    password: '$2b$10$MqM.I0rUUFfgHdbCcMroeebmqmIQrCBiD83mgq32CYUxTGIEnh.0.',
    bio: 'karate instructor',
    occupation: 'teacher',
    expertise: 'fighting',
    isMentor: false,
    admin: false,
  },
];

export default users;
